export const property = {
  name: 'property',
  title: 'Properties',
  type: 'document',
  fields: [
    { name: 'title', title: 'Property Title', type: 'string' },
    { name: 'slug', title: 'Slug (URL)', type: 'slug', options: { source: 'title', maxLength: 96 } },
    { name: 'price', title: 'Monthly Rent (e.g. £1,095 pcm)', type: 'string' },
    { name: 'deposit', title: 'Deposit / Bond (e.g. £1,095)', type: 'string' },
    { name: 'propertyRef', title: 'Property Reference ID (e.g. 3015767)', type: 'string' },
    { name: 'maxTenants', title: 'Maximum Number of Tenants', type: 'number' },
    { name: 'location', title: 'Location & Postcode (e.g. Bridgewater Crescent, DY2)', type: 'string' },
    { name: 'beds', title: 'Bedrooms', type: 'number' },
    { name: 'baths', title: 'Bathrooms', type: 'number' },
    { name: 'billsIncluded', title: 'Bills Included?', type: 'boolean' },
    { name: 'petsAllowed', title: 'Pets Allowed?', type: 'boolean' },
    { name: 'smokingAllowed', title: 'Smokers Allowed?', type: 'boolean' },
    { name: 'furnishing', title: 'Furnishing (e.g. Unfurnished)', type: 'string' },
    { name: 'epcRating', title: 'EPC Rating (e.g. D)', type: 'string' },
    { name: 'description', title: 'Description', type: 'text' },
    {
      name: 'interiorImages',
      title: 'Interior Photos (Multiple)',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
    },
    {
      name: 'exteriorImages',
      title: 'Exterior Photos (Multiple)',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
    },
    { name: 'floorPlanImage', title: '2D Floor Plan Image', type: 'image', options: { hotspot: true } },
  ],
};